source:      .
destination: ./_site
includes:    ./_includes

collections:
  projects:
    output: true
analytics: 
  provider : "google-gtag"
   # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id : "G-5HQPK7RHNC"
    anonymize_ip : # true, false (default)
